// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Generated by gen/wrappers/main.go from wrappers.go.tmpl.

package amcl

import "github.com/miracl/amcl/wrap"

// RSADecrypt_2048 is a wrapper if wrap.RSA_2048_DECRYPT
func RSADecrypt_2048(priv wrap.RSAPrivateKey, G []byte) (F []byte) {

	GOct := wrap.NewOctet(G)
	defer GOct.Free()

	FSize := wrap.RFS_2048
	FOct := wrap.MakeOctet(FSize)
	defer FOct.Free()

	wrap.RSA_2048_DECRYPT(priv, GOct, FOct)

	F = FOct.ToBytes()
	return
}

// RSAEncrypt_2048 is a wrapper if wrap.RSA_2048_ENCRYPT
func RSAEncrypt_2048(pub wrap.RSAPublicKey, F []byte) (G []byte) {

	FOct := wrap.NewOctet(F)
	defer FOct.Free()

	GSize := wrap.RFS_2048
	GOct := wrap.MakeOctet(GSize)
	defer GOct.Free()

	wrap.RSA_2048_ENCRYPT(pub, FOct, GOct)

	G = GOct.ToBytes()
	return
}

// RSAKeyPair_2048 is a wrapper if wrap.RSA_2048_KEY_PAIR
func RSAKeyPair_2048(rng *wrap.Rand, e int32, p []byte, q []byte) (priv wrap.RSAPrivateKey, pub wrap.RSAPublicKey) {

	priv = wrap.NewRSAPrivateKey_2048()

	pub = wrap.NewRSAPublicKey_2048()

	pOct := wrap.NewOctet(p)
	defer pOct.Free()

	qOct := wrap.NewOctet(q)
	defer qOct.Free()

	wrap.RSA_2048_KEY_PAIR(rng, e, priv, pub, pOct, qOct)

	return
}

// RSAPrivateKeyKill_2048 is a wrapper if wrap.RSA_2048_PRIVATE_KEY_KILL
func RSAPrivateKeyKill_2048(PRIV wrap.RSAPrivateKey) {

	wrap.RSA_2048_PRIVATE_KEY_KILL(PRIV)

	return
}
